name: Just like my liquor

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build Always OK Server for ${{ matrix.dickname }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: "CGO_ENABLED=0"
            dickname: "amd64-musl"
          - tag: "CGO_ENABLED=0 GOARCH=arm64"
            dickname: "arm64-musl"

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: "stable"

      - name: Build!
        shell: bash
        run: |
          ${{ matrix.tag }} go build -o rsop-${{ matrix.dickname }}

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: Always-200OK-Server
          files: rsop-${{ matrix.dickname }}
          body: |
            # An always 200-OK Server
            Made use Golang `net/http` lib
            ## 🚀 Uses
            - When you using `Rustdesk-server`, The rustdesk client sometimes will be sent a post to server:21114
            ## ? Why do this
            - But if you not bought `Rustdesk-Server-Pro`, It will be **TimeOut Error**.
            - So this is a fake server that solve this problem.
            - It is an always OK Server to Fuck this error.
            ## 🙏 Acknowledgements
            <https://867678.xyz>
            <https://claude.ai>
            ## ⚖️ License
            GNU AGPL-v3-or-later.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Send to mirror
        uses: moaeiou/moaeiou/actions/rsync@main
        with:
          local: rsop-${{ matrix.dickname }}
          remote: /var/www/html/luci-app/rsop/a2s/
          key: ${{ secrets.CC_LA_KEY }}